### ISSUE TITLE
where is the checkpoint for stable-audio 1.0 (instead of stable audio open 1.0)?

### ISSUE THREAD

**Issue by yuelei0428** [Stability-AI/stable-audio-tools#149]
as title

**Comment by nateraw** [comment]
It's not open source, only available through their service. Stable audio open was (I assume) more meticulously screened for copyrighted data so it could be released. I assume data used to train SA 1.0 was not as carefully screened, leading to it not being released.

**Comment by zqevans** [comment]
It wasn't a data screening issue, it's that it's a totally separate dataset. Stable Audio 1.0 and 2.0 were trained on data licensed from AudioSparx, with a revenue share agreement, so we had to keep it closed due to the agreement. 

Stable Audio Open 1.0 was trained on Creative Commons data so we didn't have the same data licensing issue, so it could be open.

**Comment by nateraw** [comment]
Thanks for clarifying @zqevans!!
