### ISSUE TITLE
Cannot install. Idk about "wheel" or what subprocess could be the problem

### ISSUE THREAD

**Issue by frankleitor** [Stability-AI/stable-audio-tools#97]

**Comment by stredger** [comment]
The issue here is the `flash-attn` package on windows and python 3.12. I downgraded to python 3.9 and managed to resolve this. I might recommend using 3.8.10 as thats whats mentioned as the development version in the repo. Additionally I had to use the legacy resolver for pip (`--use-deprecated=legacy-resolver`) as installing without was taking forever
